contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 655ac318-9ae5-423d-8fae-075aec0c87ab
inputs: []
name: GEL - Save ITSM List
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c6d3147d-8c7b-473b-8031-bd2626e55aea
      iscommand: false
      name: ""
      version: -1
    taskid: c6d3147d-8c7b-473b-8031-bd2626e55aea
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: 3@${incident.id}
      list_name:
        simple: ITSM_Endpoint
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Use entry ID to load and parse excel file
      id: 15c581c7-a819-426d-84a1-2f857bbfca53
      iscommand: false
      name: ParseExcel and Save to list
      script: ParseExcelToList
      type: regular
      version: -1
    taskid: 15c581c7-a819-426d-84a1-2f857bbfca53
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 160
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 205,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
