contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.1.4
    packID: QRadar
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: This playbook runs a QRadar query and return its results to the context.
id: QRadarFullSearch
inputs:
- description: How much time to wait before a timeout occurs (minutes)
  key: timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "600"
- description: Polling frequency - how often the polling command should run (minutes)
  key: interval
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
- description: The query expressions in AQL
  key: query_expression
  playbookInputQuery: null
  required: true
  value:
    simple: SELECT * FROM events WHERE inOffense(150) AND qid = '67500096 ' LIMIT
      5 START '2021-11-25 01:17:07'
- description: Range of results to return (e.g. 0-20)
  key: range
  playbookInputQuery: null
  required: false
  value: {}
- description: Table headers
  key: headers
  playbookInputQuery: null
  required: false
  value: {}
name: QRadarFullSearch
outputs:
- contextPath: QRadar.Search.Result
  description: The result of the search
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Start of playbook
      id: 230a5fa5-ffb2-4d27-857f-647083ec27dc
      iscommand: false
      name: ""
      version: -1
    taskid: 230a5fa5-ffb2-4d27-857f-647083ec27dc
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 170,
          "y": -100
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      headers:
        simple: ${inputs.headers}
      query_expression:
        simple: ${inputs.query_expression}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Creates a search in QRadar using the search query
      id: c8436b25-99f9-46ec-8fe6-cc601675c5f3
      iscommand: true
      name: Run QRadar search
      script: '|||qradar-searches'
      type: regular
      version: -1
    taskid: c8436b25-99f9-46ec-8fe6-cc601675c5f3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -37.5,
          "y": 205
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      headers:
        simple: ${inputs.headers}
      search_id:
        simple: ${QRadar.Search.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets search object to initialize polling playbook
      id: 4dd0f61d-1391-47c3-8a9d-b5580671f092
      iscommand: true
      name: Get QRadar search
      script: '|||qradar-get-search'
      type: regular
      version: -1
    taskid: 4dd0f61d-1391-47c3-8a9d-b5580671f092
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -37.5,
          "y": 380
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        simple: ${QRadar.Search.ID}
      Interval:
        simple: ${inputs.interval}
      PollingCommandArgName:
        simple: search_id
      PollingCommandName:
        simple: qradar-get-search
      Timeout:
        simple: ${inputs.timeout}
      dt:
        simple: QRadar.Search(val.Status!=='COMPLETED' ).ID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Generic polling of qradar-get-search
      id: af4d3d48-5707-4522-8fef-a6d3b393eab4
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: af4d3d48-5707-4522-8fef-a6d3b393eab4
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -150,
          "y": 730
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      headers:
        simple: ${inputs.headers}
      range:
        simple: ${inputs.range}
      search_id:
        simple: ${QRadar.Search.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: executes qradar-get-search-results to get the search results
      id: 6eefed42-f1f6-46d7-83b0-ecb2e47575f9
      iscommand: true
      name: Get QRadar search results
      script: '|||qradar-get-search-results'
      type: regular
      version: -1
    taskid: 6eefed42-f1f6-46d7-83b0-ecb2e47575f9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -37.5,
          "y": 905
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Playbook is done
      id: 172877e1-d636-4b2a-8b3e-70dddf7ea585
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 172877e1-d636-4b2a-8b3e-70dddf7ea585
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 170,
          "y": 1080
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: QRadar.Search.Status
          operator: isEqualString
          right:
            value:
              simple: COMPLETED
      label: "yes"
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the search is completed
      id: 7c323154-9752-4e8d-8e18-7d43fef89edf
      iscommand: false
      name: Is search completed?
      type: condition
      version: -1
    taskid: 7c323154-9752-4e8d-8e18-7d43fef89edf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -37.5,
          "y": 555
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: inList
                    right:
                      value:
                        simple: QRadar,QRadar_v2,QRadar v3
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 42a5a20b-6d0e-4019-8ab1-cfe5c796c085
      iscommand: false
      name: Is QRadar enabled?
      type: condition
      version: -1
    taskid: 42a5a20b-6d0e-4019-8ab1-cfe5c796c085
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 170,
          "y": 35
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1245,
        "width": 700,
        "x": -150,
        "y": -100
      }
    }
  }
