contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.0.2
    packID: Palo_Alto_Networks_WildFire
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: |-
  Detonate one or more files using the Wildfire integration. This playbook
  returns relevant reports to the War Room and file reputations to the context data.
  The detonation supports the following file types -
  APK, JAR, DOC, DOCX, RTF, XLS, XLSX, PPT, PPTX, OOXML, PE32, PE, PDF, DMG, PKG, RAR, 7Z, JS, ELF, HTA, LNK, VBS, PS1, PERL, PYTHON, SHELL.
id: WildFire - Detonate file
inputs:
- description: File object of the file to detonate. The file is taken from the context.
  key: File
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: File
- description: The duration for executing the polling (in minutes).
  key: Interval
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
- description: The duration after which to stop polling and to resume the playbook.
    (in minutes)
  key: Timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "15"
- description: The resource type to download.
  key: ReportFileType
  playbookInputQuery: null
  required: false
  value: {}
name: WildFire - Detonate file
outputs:
- contextPath: DBotScore.Score
  description: The actual score.
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator.
  type: string
- contextPath: File.Type
  description: The file type, e.g. "PE".
  type: string
- contextPath: File.Size
  description: The file size
  type: number
- contextPath: File.MD5
  description: The MD5 hash of the file.
  type: string
- contextPath: File.Name
  description: The filename.
  type: string
- contextPath: File.SHA1
  description: The SHA1 hash of the file.
  type: string
- contextPath: File
  description: The file object.
  type: unknown
- contextPath: File.SHA256
  description: TheSHA256 hash of the file.
  type: string
- contextPath: File.Malicious
  description: The malicious object.
  type: unknown
- contextPath: File.Malicious.Vendor
  description: The vendor that made the decision that the file is malicious.
  type: string
- contextPath: DBotScore
  description: The DBot object.
  type: unknown
- contextPath: DBotScore.Indicator
  description: The indicator that was tested.
  type: string
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the score.
  type: string
- contextPath: WildFire.Report
  description: The submission object.
  type: unknown
- contextPath: WildFire.Report.Status
  description: The status of the submission.
  type: string
- contextPath: WildFire.Report.SHA256
  description: The SHA256 hash of the submission.
  type: string
- contextPath: InfoFile
  description: The report file object.
  type: unknown
- contextPath: InfoFile.EntryID
  description: The EntryID of the report file.
  type: string
- contextPath: InfoFile.Extension
  description: The extension of the report file.
  type: string
- contextPath: InfoFile.Name
  description: The name of the report file.
  type: string
- contextPath: InfoFile.Info
  description: The info of the report file.
  type: string
- contextPath: InfoFile.Size
  description: The size of the report file.
  type: number
- contextPath: InfoFile.Type
  description: The type of the report file.
  type: string
- contextPath: WildFire.Report.MD5
  description: The MD5 hash of the submission.
  type: string
- contextPath: WildFire.Report.FileType
  description: The type of the submission.
  type: string
- contextPath: WildFire.Report.Size
  description: The size of the submission.
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ff6c3afb-1f37-491b-8569-f2f9d6a79ff3
      iscommand: false
      name: ""
      version: -1
    taskid: ff6c3afb-1f37-491b-8569-f2f9d6a79ff3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: Report.SHA256
          root: WildFire
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: hash
      PollingCommandName:
        simple: wildfire-report
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: WildFire.Report(val.Status != 'Success').SHA256
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continually running the command in Step #2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: d89662d0-dedb-49ff-8cba-4855a985cc38
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: d89662d0-dedb-49ff-8cba-4855a985cc38
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1245
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      format:
        complex:
          root: inputs.ReportFileType
      hash:
        complex:
          accessor: Report.SHA256
          root: WildFire
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve results for a file hash using WildFire.
      id: 4d801593-76c0-45bc-880c-46572315ab6d
      iscommand: true
      name: WildFire Get Report
      script: '|||wildfire-report'
      type: regular
      version: -1
    taskid: 4d801593-76c0-45bc-880c-46572315ab6d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1420
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7cb53d1d-e613-47cd-847e-c1908e384d53
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7cb53d1d-e613-47cd-847e-c1908e384d53
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: EntryID
                root: inputs.File
          operator: isExists
      label: "yes"
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Look for files to detonate.
      id: 5944d365-4547-4e91-8f62-fa295fa32b38
      iscommand: false
      name: Is there a file to detonate?
      type: condition
      version: -1
    taskid: 5944d365-4547-4e91-8f62-fa295fa32b38
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 170,
          "y": 370
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: WildFire
                  - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: WildFire-v2
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if integration instance is enabled.
      id: f959299e-1445-4a65-85bf-d4f70a0c7ebf
      iscommand: false
      name: Is WildFire sandbox enabled?
      type: condition
      version: -1
    taskid: f959299e-1445-4a65-85bf-d4f70a0c7ebf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "10":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: EntryID
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: inputs.File.Type
                    operator: match
                    right:
                      value:
                        simple: .*(?:APK|JAR|DOC|DOCX|RTF|XLS|XLSX|PPT|PPTX|OOXML|PE32|PE|PDF|DMG|PKG|RAR|7Z|JS|ELF|HTA|LNK|VBS|PS1|PERL|sh|PYTHON|SHELL)\b
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: inputs.File.Info
                    operator: match
                    right:
                      value:
                        simple: .*(?:APK|JAR|DOC|DOCX|RTF|XLS|XLSX|PPT|PPTX|OOXML|PE32|PE|PDF|DMG|PKG|RAR|7Z|JS|ELF|HTA|LNK|VBS|PS1|PERL|sh|PYTHON|SHELL)\b
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: inputs.File.Extension
                    operator: match
                    right:
                      value:
                        simple: .*(?:APK|JAR|DOC|DOCX|RTF|XLS|XLSX|PPT|PPTX|OOXML|PE32|PE|PDF|DMG|PKG|RAR|7Z|JS|ELF|HTA|LNK|VBS|PS1|PERL|sh|PYTHON|SHELL)\b
                root: inputs.File
          operator: isExists
      label: "yes"
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if file type is supported.
      id: 329341a2-3ac5-422f-8264-b9fbaae07d3f
      iscommand: false
      name: Is the file type supported?
      type: condition
      version: -1
    taskid: 329341a2-3ac5-422f-8264-b9fbaae07d3f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 275,
          "y": 720
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: File
      value:
        complex:
          root: inputs.File
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value into the context with the given context key.
      id: 16c9088e-43fa-494a-80f2-646461c74a66
      iscommand: false
      name: Set Context
      script: Set
      type: regular
      version: -1
    taskid: 16c9088e-43fa-494a-80f2-646461c74a66
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      upload:
        complex:
          accessor: EntryID
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.File.Info
              operator: match
              right:
                value:
                  simple: .*(?:APK|JAR|DOC|DOCX|RTF|XLS|XLSX|PPT|PPTX|OOXML|PE32|PE|PDF|DMG|PKG|RAR|7Z|JS|ELF|HTA|LNK|VBS|PS1|PERL|sh|PYTHON|SHELL)\b
            - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.File.Type
              operator: match
              right:
                value:
                  simple: .*(?:APK|JAR|DOC|DOCX|RTF|XLS|XLSX|PPT|PPTX|OOXML|PE32|PE|PDF|DMG|PKG|RAR|7Z|JS|ELF|HTA|LNK|VBS|PS1|PERL|sh|PYTHON|SHELL)\b
            - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.File.Extension
              operator: match
              right:
                value:
                  simple: .*(?:APK|JAR|DOC|DOCX|RTF|XLS|XLSX|PPT|PPTX|OOXML|PE32|PE|PDF|DMG|PKG|RAR|7Z|JS|ELF|HTA|LNK|VBS|PS1|PERL|sh|PYTHON|SHELL)\b
          root: inputs.File
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Uploads a file to WildFire for analysis.
      id: f964fe7b-3805-44e8-8f2e-a4b71300ad70
      iscommand: true
      name: WildFire Upload File
      script: '|||wildfire-upload'
      type: regular
      version: -1
    taskid: f964fe7b-3805-44e8-8f2e-a4b71300ad70
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 895
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Report.SHA256
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: WildFire.Report.Status
                    operator: isEqualString
                    right:
                      value:
                        simple: Pending
                root: WildFire
          operator: isExists
      label: "yes"
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the upload was successfully finished.
      id: d1c6a572-54e7-4233-8228-daa0f7dcb176
      iscommand: false
      name: Did the upload finish successfully?
      type: condition
      version: -1
    taskid: d1c6a572-54e7-4233-8228-daa0f7dcb176
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1060
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1610,
        "width": 717.5,
        "x": 50,
        "y": 50
      }
    }
  }
