contentitemexportablefields:
  contentitemfields:
    fromServerVersion: 5.0.0
    itemVersion: 2.1.4
    packID: CommonPlaybooks
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: |-
  Enrich email addresses.
  - Get information from Active Directory for internal addresses
  - Get the domain-squatting reputation for external addresses
id: Email Address Enrichment - Generic v2.1
inputs:
- description: A CSV list of internal domains. The list will be used to determine
    whether an email address is internal or external.
  key: InternalDomains
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: inputs.InternalDomains
      transformers:
      - operator: uniq
- description: The email addresses to enrich.
  key: Email
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Email.Address
      root: Account
      transformers:
      - operator: uniq
- description: The domains associated with the incident. These domains will be checked
    for domain-squatting.
  key: Domain
  playbookInputQuery: null
  required: false
  value:
    complex:
      filters:
      - - left:
            iscontext: true
            value:
              simple: inputs.Domain
          operator: isNotEmpty
      root: inputs.Domain
      transformers:
      - operator: uniq
name: Email Address Enrichment - Generic v2.1
outputs:
- contextPath: Account
  description: The Account object.
  type: unknown
- contextPath: Account.Email.NetworkType
  description: The email account NetworkType (Internal/External).
  type: string
- contextPath: Account.Email.Distance.Domain
  description: The compared domain.
  type: string
- contextPath: Account.Email.Distance.Value
  description: 'The distance between the email domain and the compared domain. '
  type: number
- contextPath: DBotScore
  description: The DBotScore object.
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 10b003be-68f2-4e57-8f11-d0475f1aac42
      iscommand: false
      name: ""
      version: -1
    taskid: 10b003be-68f2-4e57-8f11-d0475f1aac42
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 50
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: entry.contents:${Account.Username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 01ab9a35-e60e-4331-826d-48194fb5a771
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 01ab9a35-e60e-4331-826d-48194fb5a771
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1390
        }
      }
  "5":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.Email
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: inputs.Email
          operator: isNotEmpty
      label: "yes"
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "20"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines whether the playbook's input contains at least one email
        address.
      id: 43ea7e61-2e1e-4d4c-835c-623055112691
      iscommand: false
      name: Are there email addresses to check?
      type: condition
      version: -1
    taskid: 43ea7e61-2e1e-4d4c-835c-623055112691
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 200
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
      - "14"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      domain:
        complex:
          root: inputs.InternalDomains
          transformers:
          - operator: uniq
      email:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Email
              operator: isNotEmpty
          root: inputs.Email
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Adds a NetworkType attribute to all email addresses. The NetworkType
        attribute determines whether the email address is an internal or external
        email address, according to the domains that were passed as arguments to this
        playbook.
      id: 7aa90f8f-bdf1-4d72-88ae-f0d7d2d0142f
      iscommand: false
      name: Classify email addresses as internal or external
      script: IsEmailAddressInternal
      type: regular
      version: -1
    taskid: 7aa90f8f-bdf1-4d72-88ae-f0d7d2d0142f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 400
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e82515ea-9f9a-4273-8182-e6a84b24e4d6
      iscommand: false
      name: Internal
      type: title
      version: -1
    taskid: e82515ea-9f9a-4273-8182-e6a84b24e4d6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 672.5,
          "y": 785
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d501d6f3-d086-40fa-8c28-052fc32787fb
      iscommand: false
      name: External
      type: title
      version: -1
    taskid: d501d6f3-d086-40fa-8c28-052fc32787fb
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 100.5,
          "y": 785
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      email:
        complex:
          accessor: Email
          root: Account
          transformers:
          - args:
              equalTo:
                value:
                  simple: Internal
              field:
                value:
                  simple: NetworkType
              getField:
                value:
                  simple: Address
              stringify:
                value:
                  simple: "true"
            operator: WhereFieldEquals
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Uses Active Directory to get user information for internal email
        addresses.
      id: 266c8054-586a-4b62-811b-d13147f12e54
      iscommand: true
      name: Get email address info from Active Directory
      script: '|||ad-get-user'
      type: regular
      version: -1
    taskid: 266c8054-586a-4b62-811b-d13147f12e54
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 672.5,
          "y": 1195
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: Email
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: Account.Email.NetworkType
              operator: isEqualString
              right:
                value:
                  simple: External
          root: Account
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether there are email addresses with a NetworkType attribute
        value of "External".
      id: 2d740d11-a326-4913-83f1-8df803c0a3eb
      iscommand: false
      name: Are there any external email addresses?
      script: Exists
      type: condition
      version: -1
    taskid: 2d740d11-a326-4913-83f1-8df803c0a3eb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 100.5,
          "y": 580
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: Email
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: Account.Email.NetworkType
              operator: isEqualString
              right:
                value:
                  simple: Internal
          root: Account
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether there are email addresses with a NetworkType attribute
        value of "Internal".
      id: e521733d-b152-4a1f-8050-e7658405a187
      iscommand: false
      name: Are there any internal email addresses?
      script: Exists
      type: condition
      version: -1
    taskid: e521733d-b152-4a1f-8050-e7658405a187
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 672.5,
          "y": 580
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      domain:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Domain
              operator: isNotEmpty
          root: inputs.Domain
          transformers:
          - operator: uniq
      email:
        complex:
          accessor: Email
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Account.Email.Address
              operator: isNotEmpty
          root: Account
          transformers:
          - args:
              equalTo:
                value:
                  simple: External
              field:
                value:
                  simple: NetworkType
              getField:
                value:
                  simple: Address
            operator: WhereFieldEquals
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if an email address's domain is trying to squat other domains
        using Levenshtein distance algorithm.
      id: 7d4c6562-651c-487d-834e-f3921527c76e
      iscommand: false
      name: Check email addresses for domain-squatting
      script: EmailDomainSquattingReputation
      type: regular
      version: -1
    taskid: 7d4c6562-651c-487d-834e-f3921527c76e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 100.5,
          "y": 1195
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: brand
          filters:
          - - left:
                iscontext: true
                value:
                  simple: modules.brand
              operator: isEqualString
              right:
                value:
                  simple: Active Directory Query v2
          - - left:
                iscontext: true
                value:
                  simple: modules.state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there's an active instance of the Active Directory Query
        v2 integration enabled.
      id: 71e0fb34-e1c8-4606-8462-1f83a0a2cb56
      iscommand: false
      name: Is Active Directory Query v2 enabled?
      script: Exists
      type: condition
      version: -1
    taskid: 71e0fb34-e1c8-4606-8462-1f83a0a2cb56
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 672.5,
          "y": 960
        }
      }
  "18":
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Domain
              operator: isNotEmpty
          root: inputs.Domain
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is at least one domain to check for domain-squatting.
      id: 1f1a6cd8-5aaa-4b0a-8147-e91dc6beec49
      iscommand: false
      name: Is there a domain list input?
      script: Exists
      type: condition
      version: -1
    taskid: 1f1a6cd8-5aaa-4b0a-8147-e91dc6beec49
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 100.5,
          "y": 960
        }
      }
  "20":
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3ecf1917-78f6-4350-84bb-704fdaa1bf05
      iscommand: false
      name: No Email Addresses
      type: title
      version: -1
    taskid: 3ecf1917-78f6-4350-84bb-704fdaa1bf05
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -380,
          "y": 785
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "13_11_yes": 0.64,
      "13_4_#default#": 0.16,
      "14_10_yes": 0.65,
      "14_4_#default#": 0.17,
      "17_4_#default#": 0.23,
      "18_4_#default#": 0.23,
      "5_20_#default#": 0.35
    },
    "paper": {
      "dimensions": {
        "height": 1405,
        "width": 1432.5,
        "x": -380,
        "y": 50
      }
    }
  }
