contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.1.8
    packID: CommonPlaybooks
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: |-
  Enrich a file using one or more integrations.

  - Provide threat information
id: File Enrichment - Generic v2
inputs:
- description: File MD5 hash to enrich.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
      transformers:
      - operator: uniq
- description: The file SHA256 hash to enrich.
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
      transformers:
      - operator: uniq
- description: The file SHA1 hash to enrich.
  key: SHA1
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
      transformers:
      - operator: uniq
name: File Enrichment - Generic v2
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested.
  type: string
- contextPath: DBotScore.Type
  description: The indicator type.
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file.
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file.
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision.
  type: string
- contextPath: File.MD5
  description: MD5 hash of the file.
  type: string
- contextPath: DBotScore
  description: The DBotScore object.
  type: unknown
- contextPath: File
  description: The file object
  type: unknown
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score.
  type: string
- contextPath: DBotScore.Score
  description: The actual score.
  type: number
- contextPath: File.VirusTotal.Scans
  description: The scan object.
  type: unknown
- contextPath: File.VirusTotal.Scans.Source
  description: Vendor that scanned this hash.
- contextPath: File.VirusTotal.Scans.Detected
  description: Whether a scan was detected for this hash (True/False).
- contextPath: File.VirusTotal.Scans.Result
  description: Scan result for this hash - signature, etc.
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 00109219-5fc8-4bbb-881e-e597ec3b7439
      iscommand: false
      name: ""
      version: -1
    taskid: 00109219-5fc8-4bbb-881e-e597ec3b7439
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 735,
          "y": -90
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 89ce26db-58e9-4a6d-88f2-d6810e458ee2
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 89ce26db-58e9-4a6d-88f2-d6810e458ee2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 735,
          "y": 620
        }
      }
  "25":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA256
          operator: isExists
      label: "yes"
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "27"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if there is a SHA256 hash in context.
      id: 339fc232-e5d0-468b-87ea-cf8d41ea0ca6
      iscommand: false
      name: Is there a SHA256 hash?
      type: condition
      version: -1
    taskid: 339fc232-e5d0-468b-87ea-cf8d41ea0ca6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 470,
          "y": 50
        }
      }
  "27":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Cylance Protect v2
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Cylance Protect v2
        integration enabled.
      id: 0783a3a6-5d8b-48f1-8dee-f3f0ef62defc
      iscommand: false
      name: Is Cylance Protect v2 enabled?
      type: condition
      version: -1
    taskid: 0783a3a6-5d8b-48f1-8dee-f3f0ef62defc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 470,
          "y": 250
        }
      }
  "28":
    continueonerror: true
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      sha256:
        complex:
          root: inputs.SHA256
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cylance Protect v2
      description: Gets threat information from the Cylance Protect v2 integration.
      id: ff014724-3ad2-4ce2-8578-5106c126e76b
      iscommand: true
      name: Get threat information from Cylance Protect v2
      script: Cylance Protect v2|||cylance-protect-get-threat
      type: regular
      version: -1
    taskid: ff014724-3ad2-4ce2-8578-5106c126e76b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 450
        }
      }
  "29":
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Get file information using the Virus Total Private API integration.
      id: e5eae00a-9da2-4d93-8ed2-693e0c6c2c89
      iscommand: false
      name: File Enrichment - Virus Total Private API
      playbookName: File Enrichment - Virus Total Private API
      type: playbook
      version: -1
    taskid: e5eae00a-9da2-4d93-8ed2-693e0c6c2c89
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 990,
          "y": 50
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "25_27_yes": 0.59,
      "25_7_#default#": 0.44,
      "27_28_yes": 0.57,
      "27_7_#default#": 0.63
    },
    "paper": {
      "dimensions": {
        "height": 775,
        "width": 900,
        "x": 470,
        "y": -90
      }
    }
  }
