contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 93eef3d9-399f-4a17-8acc-3a56d38a4534
inputs: []
name: GEL - Malware
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 27073676-ce18-46e9-82a2-13fce27a541c
      iscommand: false
      name: ""
      version: -1
    taskid: 27073676-ce18-46e9-82a2-13fce27a541c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d04cf7c7-9320-475a-8ed2-add9ea30e83d
      iscommand: false
      name: Enrich Indicators
      type: title
      version: -1
    taskid: d04cf7c7-9320-475a-8ed2-add9ea30e83d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1215
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d1b752c7-9869-491b-8f08-53b21cb44d7c
      iscommand: false
      name: File Hash
      type: title
      version: -1
    taskid: d1b752c7-9869-491b-8f08-53b21cb44d7c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1870
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
      - "20"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8c78c00f-6cad-4f96-8718-ffc4e309435f
      iscommand: false
      name: Network Connectivity
      type: title
      version: -1
    taskid: 8c78c00f-6cad-4f96-8718-ffc4e309435f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 1360
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: ${QRadar.Event.Payload.Application_hash}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks the file reputation of the specified hash.
      id: a2b80c7c-7ecc-454b-89b7-15c45a9fe721
      iscommand: true
      name: Check with VirusTotal
      script: '|||file'
      type: regular
      version: -1
    taskid: a2b80c7c-7ecc-454b-89b7-15c45a9fe721
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2030
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: getverdict
          operator: isEqualString
          right:
            value:
              simple: malicious
      label: malicious
    - condition:
      - - left:
            iscontext: true
            value:
              simple: getverdict
          operator: isEqualString
          right:
            value:
              simple: benign
      label: benign
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      benign:
      - "26"
      malicious:
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 50da6b28-da65-4ebd-8a54-73774d04fc3e
      iscommand: false
      name: Remediation
      type: condition
      version: -1
    taskid: 50da6b28-da65-4ebd-8a54-73774d04fc3e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2205
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0d837927-1489-46cd-86fa-997401ed1c63
      iscommand: false
      name: Ban the Hash
      type: regular
      version: -1
    taskid: 0d837927-1489-46cd-86fa-997401ed1c63
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2380
        }
      }
  "18":
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a84a341d-148a-41c3-8e11-072469d320a2
      iscommand: false
      name: Delete the file
      type: regular
      version: -1
    taskid: a84a341d-148a-41c3-8e11-072469d320a2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2555
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6401c741-4897-4ef2-8559-d43af89154ba
      iscommand: false
      name: Check with URL Scan
      type: regular
      version: -1
    taskid: 6401c741-4897-4ef2-8559-d43af89154ba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1505
        }
      }
  "20":
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0f9ba89b-8b43-4ff1-8606-dea2e46e85ef
      iscommand: false
      name: Check with Virus Total
      type: regular
      version: -1
    taskid: 0f9ba89b-8b43-4ff1-8606-dea2e46e85ef
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 817.5,
          "y": 1505
        }
      }
  "21":
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2323ceb6-6d65-4f98-8ac1-13f16fecd53f
      iscommand: false
      name: Get Verdict
      type: regular
      version: -1
    taskid: 2323ceb6-6d65-4f98-8ac1-13f16fecd53f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 1680
        }
      }
  "22":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: getverdict
          operator: isEqualString
          right:
            value:
              simple: malicious
      label: malicious
    - condition:
      - - left:
            iscontext: true
            value:
              simple: getverdict
          operator: isEqualString
          right:
            value:
              simple: benign
      label: benign
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      benign:
      - "26"
      malicious:
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 591d35f3-d575-4a51-854c-78907c6485d9
      iscommand: false
      name: Remediation
      type: condition
      version: -1
    taskid: 591d35f3-d575-4a51-854c-78907c6485d9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 2030
        }
      }
  "23":
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 635dcaaa-5bcb-4bc5-8c82-b258009d1eec
      iscommand: false
      name: Run AV Scan
      type: regular
      version: -1
    taskid: 635dcaaa-5bcb-4bc5-8c82-b258009d1eec
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 715,
          "y": 2205
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c2c76cf5-423d-4b9c-8110-feb8ada6b185
      iscommand: false
      name: Block Domain or IP
      type: regular
      version: -1
    taskid: c2c76cf5-423d-4b9c-8110-feb8ada6b185
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 715,
          "y": 2380
        }
      }
  "25":
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d96525cc-af0d-47ce-8004-869663c134ab
      iscommand: false
      name: Block URL
      type: regular
      version: -1
    taskid: d96525cc-af0d-47ce-8004-869663c134ab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 715,
          "y": 2555
        }
      }
  "26":
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ca9d2bf0-9af3-4e15-8381-3d319741ceb9
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: ca9d2bf0-9af3-4e15-8381-3d319741ceb9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 275,
          "y": 2730
        }
      }
  "28":
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 61f753f4-60e5-4c27-8ab1-b15a8b58e56d
      iscommand: false
      name: Communicate with IT Network team
      type: regular
      version: -1
    taskid: 61f753f4-60e5-4c27-8ab1-b15a8b58e56d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 1855
        }
      }
  "29":
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "33"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: afcb9630-7744-4201-825e-6660aaaf7b75
      iscommand: false
      name: Get QRadar Events
      type: title
      version: -1
    taskid: afcb9630-7744-4201-825e-6660aaaf7b75
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "30":
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "34"
    note: false
    quietmode: 0
    scriptarguments:
      interval:
        simple: "1"
      query_expression:
        simple: SELECT userName, sourceip, UTF8(payload) FROM events WHERE inOffense(${incident.idoffense})
          AND qid = '67500015' LIMIT 1 START '${QRadar.startTime}'
      timeout:
        simple: "600"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: f397a446-2236-4c8c-8613-1469b6222411
      iscommand: false
      name: QRadarFullSearch
      playbookId: QRadarFullSearch
      type: playbook
      version: -1
    taskid: f397a446-2236-4c8c-8613-1469b6222411
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 515
        }
      }
  "31":
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "32"
    note: false
    quietmode: 0
    scriptarguments:
      caseInsensitive:
        simple: "false"
      data:
        simple: ${QRadar.Search.[0].Result.events.[0].utf8_payload}
      newValue:
        simple: \\\U
      regex:
        simple: \\U
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Replaces regex match/es in string.
        Returns the string after replace was preformed.
      id: 6d4935dc-0bb7-410f-823d-e7d1ed22d670
      iscommand: false
      name: Standardize payload string
      script: StringReplace
      type: regular
      version: -1
    taskid: 6d4935dc-0bb7-410f-823d-e7d1ed22d670
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 865
        }
      }
  "32":
    id: "32"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      payload:
        simple: ${StringReplace.Result}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: The script can parse QRadar Event payload to dict and save to context
      id: 9b5834d8-9051-4942-89c0-9c410a77f403
      iscommand: false
      name: Parse event data
      script: ParseQRadarEvent
      type: regular
      version: -1
    taskid: 9b5834d8-9051-4942-89c0-9c410a77f403
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1040
        }
      }
  "33":
    id: "33"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    scriptarguments:
      start_time:
        simple: ${incident.labels.start_time}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 30323326-5435-4b7f-83a2-cbe29589f45a
      iscommand: false
      name: Get Offense start time
      script: 68be939d-574a-4916-8357-9a82eadd6b36
      type: regular
      version: -1
    taskid: 30323326-5435-4b7f-83a2-cbe29589f45a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 340
        }
      }
  "34":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: QRadar.Search.Result
          operator: isNotEmpty
      label: "yes"
    id: "34"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "yes":
      - "31"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 40970db1-1c8d-48f9-821b-4974ab53317c
      iscommand: false
      name: Check if event exist
      type: condition
      version: -1
    taskid: 40970db1-1c8d-48f9-821b-4974ab53317c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 690
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2745,
        "width": 1147.5,
        "x": 50,
        "y": 50
      }
    }
  }
