contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 3bda0603-f0e8-4a76-8731-111d90cf131d
inputs: []
name: isoc_dem_vscan_create_ticket
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9b341c54-3f54-4814-877f-c7d65daa7069
      iscommand: false
      name: ""
      version: -1
    taskid: 9b341c54-3f54-4814-877f-c7d65daa7069
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: b8073ba7-1a82-4177-81d0-e8ab7f4c516e
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: b8073ba7-1a82-4177-81d0-e8ab7f4c516e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 0
      wait: 10
    note: false
    quietmode: 0
    scriptarguments:
      IssueType:
        simple: DEM
      IssueValue:
        simple: ${IssuesJson}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 12315db5-592c-4b7c-8ee4-c5ef5a94b478
      iscommand: false
      name: isoc_jira_CheckCreate
      playbookId: 3d80395b-7a92-484c-83f8-6deafd53f735
      type: playbook
      version: -1
    taskid: 12315db5-592c-4b7c-8ee4-c5ef5a94b478
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      ScalableTime:
        simple: '''10 min ago'''
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: ff715a85-74ba-42fc-8c05-7a6febb94a58
      iscommand: false
      name: isoc_Job_NowTime
      playbookName: isoc_Job_NowTime
      type: playbook
      version: -1
    taskid: ff715a85-74ba-42fc-8c05-7a6febb94a58
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      JQL:
        simple: ("DEM - Virus Found Time">= "${ScalableTime}" AND  "DEM - Virus Found
          Time" <= "${JQLTime}") OR ("VSCAN - Virus Found Time">= "${ScalableTime}"
          AND  "VSCAN - Virus Found Time" <= "${JQLTime}")
      issuetype:
        simple: DEM
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: a0db8992-48a2-4df9-80cb-93e107242de7
      iscommand: false
      name: isoc_GetIssue
      playbookId: c09c4c2c-d16e-4972-8880-fad7127c2a62
      type: playbook
      version: -1
    taskid: a0db8992-48a2-4df9-80cb-93e107242de7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: IssuesJson
          operator: isEmpty
      label: empty
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      empty:
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2badd742-f717-4241-8ff8-86f5861f8ebf
      iscommand: false
      name: Check IssuesJson if null
      type: condition
      version: -1
    taskid: 2badd742-f717-4241-8ff8-86f5861f8ebf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 49293e82-498e-49b3-88be-a2b2b60b68b5
      iscommand: false
      name: done
      type: title
      version: -1
    taskid: 49293e82-498e-49b3-88be-a2b2b60b68b5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 910
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
