contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 64517a59-bdfc-4356-8c24-be1dbe98c830
inputs: []
name: Test - Playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fd55c77e-ebfb-4c57-87d8-c20ddc090c37
      iscommand: false
      name: ""
      version: -1
    taskid: fd55c77e-ebfb-4c57-87d8-c20ddc090c37
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f04b5db6-3cfb-4c4a-8733-1265457d833a
      iscommand: true
      name: Get Password
      script: '|||get-password'
      type: regular
      version: -1
    taskid: f04b5db6-3cfb-4c4a-8733-1265457d833a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          root: ${passwd}
          transformers:
          - operator: 53073d14-4c2a-411a-80a7-b24cdc187bb9
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 5baf74de-ccc9-48a2-82be-172737507292
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 5baf74de-ccc9-48a2-82be-172737507292
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
